### ISSUE TITLE
Проблемма с запуском

### ISSUE THREAD

**Issue by bratosd** [Laysinity/Hamster-Kombat-auto-farming-bot#1]
при запуске main.py открывается консоль на миллисекунду и всё

**Comment by Laysinity** [comment]
запускай из cmd, пропиши python3 main.py

**Comment by bratosd** [comment]
"python3" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом. 
Вот это пишет

**Comment by Laysinity** [comment]
так установи python, нужна версия 3.11

**Comment by bratosd** [comment]
если писать python main.py то вот это
Traceback (most recent call last):
  File "C:\Users\New\Desktop\Hamster-Kombat-auto-farming-bot-main\main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "C:\Users\New\Desktop\Hamster-Kombat-auto-farming-bot-main\bot\utils\__init__.py", line 1, in <module>
    from .logger import logger
  File "C:\Users\New\Desktop\Hamster-Kombat-auto-farming-bot-main\bot\utils\logger.py", line 2, in <module>
    from loguru import logger
ModuleNotFoundError: No module named 'loguru'

**Comment by Laysinity** [comment]
pip install -r requirements.txt

**Comment by bratosd** [comment]
спс заработало
